### ISSUE TITLE
Causing build error on zig 0.15

### ISSUE THREAD

**Issue by SOG-web** [ziglana/gRPC-zig#14]
`zig fetch --save https://github.com/ziglana/gRPC-zig/archive/refs/heads/main.tar.gz`

```zig
 const grpc_zig = b.dependency("grpc_zig", .{
        .target = target,
        .optimize = optimize,
    });
```

Error

 zig build
/Users/rou/.cache/zig/p/grpc_zig-0.1.0-AAAAANKhAADRFh5V0-uEaCXOAnqtsjZEx01uUun3cbHp/build.zig:13:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = .{ .path = "src/server.zig" },
         ^~~~~~~~~~~~~~~~
/usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_73586: /usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2214:33
    dependencyInner__anon_70677: /usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2195:29
    8 reference(s) hidden; use '-freference-trace=10' to see all references
/Users/rou/.cache/zig/p/parg-0.0.0-AAAAAFdXAACz2idpC5mhW6vvLlbXTUaD6watDCrDXviD/build.zig:12:10: error: no field named 'root_source_file' in struct 'Build.TestOptions'
        .root_source_file = b.path("src/parser.zig"),
         ^~~~~~~~~~~~~~~~
/usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:856:25: note: struct declared here
pub const TestOptions = struct {
                        ^~~~~~
/Users/rou/.cache/zig/p/spice-0.0.0-3FtxfM67AADgcc5i5rJfewMfbutQY7DMTyNlZblzW-6p/build.zig:26:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("examples/zig-parallel-example/main.zig"),
         ^~~~~~~~~~~~~~~~
/usr/local/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~

**Comment by inge4pres** [comment]
I think this is resolved with #16 
the most recent commit on main builds fine with 0.15.2
